### ISSUE TITLE
Support for SBOM as input to grype

### ISSUE THREAD

**Issue by jornh** [fluent-ci-templates/grype-pipeline#3]
It would be useful to have this component take a SBOM as input, just like the Trivy one does: https://github.com/fluent-ci-templates/trivy-pipeline?tab=readme-ov-file#jobs

That way the task can be split into:
* Scanning done once, e.g. on image build using Syft or other tools
* Vulnerability check done periodically by Grype

As the Grype [README](https://github.com/anchore/grype?tab=readme-ov-file#getting-started) states:

> Use SBOMs for even faster vulnerability scanning in Grype:

    # Then scan for new vulnerabilities as frequently as needed
    grype sbom:./sbom.json

    # (You can also pipe the SBOM into Grype)
    cat ./sbom.json | grype

> Grype supports input of [Syft](https://github.com/anchore/syft), [SPDX](https://spdx.dev/), and [CycloneDX](https://cyclonedx.org/) SBOM formats. If Syft has generated any of these file types, they should have the appropriate information to work properly with Grype.

**Comment by tsirysndr** [comment]
Hi @jornh ,

Thank you for your suggestion and for pointing out the potential benefits of integrating SBOM (Software Bill of Materials) support into the component.

I've just added support for SBOM,

You can see an example with syft [here](https://github.com/fluent-ci-templates/grype-pipeline/blob/main/.github/workflows/example.yml).

If you have any further suggestions or questions, please feel free to share them with us.

Thank you again for your suggestion and for your contribution to the project.
